### ISSUE TITLE
Do we really need to clone TEI nodes?

### ISSUE THREAD

**Issue by raffazizzi** [pfefferniels/react-teirouter#6]
I have realized that [TEI nodes are cloned](https://github.com/pfefferniels/react-teirouter/blob/master/src/TEINode.js#L51) before being passed as property to a React component. This results in orphaned nodes without access to contextual data such as their position in the tree, sibling, etc. Is cloning really necessary?

I tried removing the cloning step and I haven't noticed errors, but perhaps @pfefferniels you have a better perspective on this? Could we at least consider introducing an option to not clone?

For more context, I was trying to implement a behavior for an empty element (`<delSpan>`) and noticed that nodes in `teiNode` are orphans, which means one can't do DOM lookups around the tree, which can be quite essential in handling empty elements, even something as simple as supporting pagination (`<pb/>`).

**Comment by pfefferniels** [comment]
You're right, the cloning isn't necessary at all – I've tested with probstuecke-digital and it works perfectly fine without it, too.

**Comment by pfefferniels** [comment]
this should fix it, can you confirm? :)

**Comment by raffazizzi** [comment]
Looks good! Before publishing, take a look at PR #7, which integrates this change and adds a new feature.
